name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Next release version
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Release next version ${{ github.event.inputs.version }}"
